apiVersion: v1
kind: ReplicationController
metadata:
  name: rc-first-javaapp
  labels: 
    version:  v1
spec:
  replicas: 2
  selector:
    app:  javapplication
  template:
    metadata: 
      labels: 
        app:  javapplication
    spec:
      containers:
        - name: java-container
          image:  maha4iac/mymahalogin
          ports:  
            - containerPort: 8080