apiVersion: v1
kind: ReplicationController
metadata:
  name: rc-first-javaapp
  labels: #optional
    version:  v1 #optional
spec:
  replicas: 3
  selector:
    app:  javapplication #Should be same with Pod name
  template:
    metadata: 
      labels: 
        app:  javapplication  # pod name
    spec:
      containers:
        - name: java-container
          image:  harasai84/myapp123:1
          ports:  
            - containerPort: 8080
