apiVersion:  v1
kind: Service
metadata:
  name: rc-service
  labels: 
    app:  abcd #optnal
    version:  v123 #optnal
spec: 
  type: NodePort
  ports:
    - port: 8080
      protocol: TCP
      nodePort: 30200
  selector:
    app:  javapplication # Should be same with Pod label
    version:  v11        #Should be same with Pod label

